//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteDebuggerLauncher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RemoteDebuggerLauncher.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CommonCancelButtonLabel {
            get {
                return ResourceManager.GetString("CommonCancelButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Mode.
        /// </summary>
        public static string CommonDialogModeLabel {
            get {
                return ResourceManager.GetString("CommonDialogModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string CommonOkButtonLabel {
            get {
                return ResourceManager.GetString("CommonOkButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online: Target device has internet access, can download and install in it&apos;s own
        ///Offline: Target device no internet access, PC will download and trigger install.
        /// </summary>
        public static string InstallationModeDescription {
            get {
                return ResourceManager.GetString("InstallationModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string InstallationModeOfflineDisplayName {
            get {
                return ResourceManager.GetString("InstallationModeOfflineDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string InstallationModeOnlineDisplayName {
            get {
                return ResourceManager.GetString("InstallationModeOnlineDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the version and installation type, then click OK to install..
        /// </summary>
        public static string InstallDebuggerDialogHeaderText {
            get {
                return ResourceManager.GetString("InstallDebuggerDialogHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install VS Code Debugger on target host.
        /// </summary>
        public static string InstallDebuggerDialogTitle {
            get {
                return ResourceManager.GetString("InstallDebuggerDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest: The latest version of the Debugger.
        /// </summary>
        public static string InstallDebuggerVersionDescription {
            get {
                return ResourceManager.GetString("InstallDebuggerVersionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest.
        /// </summary>
        public static string InstallDebuggerVersionLatestDisplayName {
            get {
                return ResourceManager.GetString("InstallDebuggerVersionLatestDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio 2022.
        /// </summary>
        public static string InstallDebuggerVersionVs2022DisplayName {
            get {
                return ResourceManager.GetString("InstallDebuggerVersionVs2022DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the version of .NET and installation type, then click OK to install..
        /// </summary>
        public static string InstallDotnetDialogHeaderText {
            get {
                return ResourceManager.GetString("InstallDotnetDialogHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install .NET on target host.
        /// </summary>
        public static string InstallDotnetDialogTitle {
            get {
                return ResourceManager.GetString("InstallDotnetDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Type.
        /// </summary>
        public static string InstallDotnetDialogTypeLabel {
            get {
                return ResourceManager.GetString("InstallDotnetDialogTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string InstallDotnetDialogVersionLabel {
            get {
                return ResourceManager.GetString("InstallDotnetDialogVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDK: Install the full .NET SDK
        ///Runtime dotnet: Install only the .NET runtime
        ///Runtime aspnet: Install the ASP.NET runtime.
        /// </summary>
        public static string InstallDotnetInstallationTypeDescription {
            get {
                return ResourceManager.GetString("InstallDotnetInstallationTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime: aspnet.
        /// </summary>
        public static string InstallDotnetInstallationTypeRuntimeAspnetDisplayName {
            get {
                return ResourceManager.GetString("InstallDotnetInstallationTypeRuntimeAspnetDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime: dotnet.
        /// </summary>
        public static string InstallDotnetInstallationTypeRuntimeNetDisplayName {
            get {
                return ResourceManager.GetString("InstallDotnetInstallationTypeRuntimeNetDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDK.
        /// </summary>
        public static string InstallDotnetInstallationTypeSdkDisplayName {
            get {
                return ResourceManager.GetString("InstallDotnetInstallationTypeSdkDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string InstallDotnetVersionCurrentDisplayName {
            get {
                return ResourceManager.GetString("InstallDotnetVersionCurrentDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current: The most recent current version of .NET
        ///LTS: The most recent LTS version of .NET.
        /// </summary>
        public static string InstallDotnetVersionDescription {
            get {
                return ResourceManager.GetString("InstallDotnetVersionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LTS.
        /// </summary>
        public static string InstallDotnetVersionLtsDisplayName {
            get {
                return ResourceManager.GetString("InstallDotnetVersionLtsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to {0}@{1} ... .
        /// </summary>
        public static string RemoteCommandCheckConnectionConnectingTo {
            get {
                return ResourceManager.GetString("RemoteCommandCheckConnectionConnectingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAILED: {0}.
        /// </summary>
        public static string RemoteCommandCommonFailed {
            get {
                return ResourceManager.GetString("RemoteCommandCommonFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SSH {0}@{1}] .
        /// </summary>
        public static string RemoteCommandCommonSshTarget {
            get {
                return ResourceManager.GetString("RemoteCommandCommonSshTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string RemoteCommandCommonSuccess {
            get {
                return ResourceManager.GetString("RemoteCommandCommonSuccess", resourceCulture);
            }
        }
    }
}
