//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteDebuggerLauncher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RemoteDebuggerLauncher.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CommonCancelButtonLabel {
            get {
                return ResourceManager.GetString("CommonCancelButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Mode.
        /// </summary>
        public static string CommonDialogModeLabel {
            get {
                return ResourceManager.GetString("CommonDialogModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string CommonOkButtonLabel {
            get {
                return ResourceManager.GetString("CommonOkButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --------------------------------------------------.
        /// </summary>
        public static string CommonStartSessionMarker {
            get {
                return ResourceManager.GetString("CommonStartSessionMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online: Target device has internet access, can download and install in it&apos;s own
        ///Offline: Target device no internet access, PC will download and trigger install.
        /// </summary>
        public static string InstallationModeDescription {
            get {
                return ResourceManager.GetString("InstallationModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string InstallationModeOfflineDisplayName {
            get {
                return ResourceManager.GetString("InstallationModeOfflineDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string InstallationModeOnlineDisplayName {
            get {
                return ResourceManager.GetString("InstallationModeOnlineDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the version and installation type, then click OK to install..
        /// </summary>
        public static string InstallDebuggerDialogHeaderText {
            get {
                return ResourceManager.GetString("InstallDebuggerDialogHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install VS Code Debugger on target host.
        /// </summary>
        public static string InstallDebuggerDialogTitle {
            get {
                return ResourceManager.GetString("InstallDebuggerDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest: The latest version of the Debugger.
        /// </summary>
        public static string InstallDebuggerVersionDescription {
            get {
                return ResourceManager.GetString("InstallDebuggerVersionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest.
        /// </summary>
        public static string InstallDebuggerVersionLatestDisplayName {
            get {
                return ResourceManager.GetString("InstallDebuggerVersionLatestDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio 2022.
        /// </summary>
        public static string InstallDebuggerVersionVs2022DisplayName {
            get {
                return ResourceManager.GetString("InstallDebuggerVersionVs2022DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the version of .NET and installation type, then click OK to install..
        /// </summary>
        public static string InstallDotnetDialogHeaderText {
            get {
                return ResourceManager.GetString("InstallDotnetDialogHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install .NET on target host.
        /// </summary>
        public static string InstallDotnetDialogTitle {
            get {
                return ResourceManager.GetString("InstallDotnetDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Type.
        /// </summary>
        public static string InstallDotnetDialogTypeLabel {
            get {
                return ResourceManager.GetString("InstallDotnetDialogTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string InstallDotnetDialogVersionLabel {
            get {
                return ResourceManager.GetString("InstallDotnetDialogVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDK: Install the full .NET SDK
        ///Runtime dotnet: Install only the .NET runtime
        ///Runtime aspnet: Install the ASP.NET runtime.
        /// </summary>
        public static string InstallDotnetInstallationTypeDescription {
            get {
                return ResourceManager.GetString("InstallDotnetInstallationTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime: aspnet.
        /// </summary>
        public static string InstallDotnetInstallationTypeRuntimeAspnetDisplayName {
            get {
                return ResourceManager.GetString("InstallDotnetInstallationTypeRuntimeAspnetDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime: dotnet.
        /// </summary>
        public static string InstallDotnetInstallationTypeRuntimeNetDisplayName {
            get {
                return ResourceManager.GetString("InstallDotnetInstallationTypeRuntimeNetDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDK.
        /// </summary>
        public static string InstallDotnetInstallationTypeSdkDisplayName {
            get {
                return ResourceManager.GetString("InstallDotnetInstallationTypeSdkDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string InstallDotnetVersionCurrentDisplayName {
            get {
                return ResourceManager.GetString("InstallDotnetVersionCurrentDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current: The most recent current version of .NET
        ///LTS: The most recent LTS version of .NET.
        /// </summary>
        public static string InstallDotnetVersionDescription {
            get {
                return ResourceManager.GetString("InstallDotnetVersionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LTS.
        /// </summary>
        public static string InstallDotnetVersionLtsDisplayName {
            get {
                return ResourceManager.GetString("InstallDotnetVersionLtsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to {0}@{1} ... .
        /// </summary>
        public static string RemoteCommandCheckConnectionOutputPaneConnectingTo {
            get {
                return ResourceManager.GetString("RemoteCommandCheckConnectionOutputPaneConnectingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking connection to {0} OK.
        /// </summary>
        public static string RemoteCommandCheckConnectionStatusbarCompletedSuccess {
            get {
                return ResourceManager.GetString("RemoteCommandCheckConnectionStatusbarCompletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking connection to {0}.
        /// </summary>
        public static string RemoteCommandCheckConnectionStatusbarProgress {
            get {
                return ResourceManager.GetString("RemoteCommandCheckConnectionStatusbarProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning - target: {0}.
        /// </summary>
        public static string RemoteCommandCleanRemoteFolderCaption {
            get {
                return ResourceManager.GetString("RemoteCommandCleanRemoteFolderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning FAILED: {0}.
        /// </summary>
        public static string RemoteCommandCleanRemoteFolderCompletedFailed {
            get {
                return ResourceManager.GetString("RemoteCommandCleanRemoteFolderCompletedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning OK.
        /// </summary>
        public static string RemoteCommandCleanRemoteFolderCompletedSuccess {
            get {
                return ResourceManager.GetString("RemoteCommandCleanRemoteFolderCompletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning ....
        /// </summary>
        public static string RemoteCommandCleanRemoteFolderStatusbarProgress {
            get {
                return ResourceManager.GetString("RemoteCommandCleanRemoteFolderStatusbarProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAILED: {0}.
        /// </summary>
        public static string RemoteCommandCommonFailed {
            get {
                return ResourceManager.GetString("RemoteCommandCommonFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing profile {0}.
        /// </summary>
        public static string RemoteCommandCommonProfile {
            get {
                return ResourceManager.GetString("RemoteCommandCommonProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SSH {0}@{1}] .
        /// </summary>
        public static string RemoteCommandCommonSshTarget {
            get {
                return ResourceManager.GetString("RemoteCommandCommonSshTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string RemoteCommandCommonSuccess {
            get {
                return ResourceManager.GetString("RemoteCommandCommonSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying application OK.
        /// </summary>
        public static string RemoteCommandDeployRemoveFolderCompletedSuccess {
            get {
                return ResourceManager.GetString("RemoteCommandDeployRemoveFolderCompletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying application - Source: {0}, Target: {1}.
        /// </summary>
        public static string RemoteCommandDeployRemoveFolderOutputPaneProgress {
            get {
                return ResourceManager.GetString("RemoteCommandDeployRemoveFolderOutputPaneProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying application ....
        /// </summary>
        public static string RemoteCommandDeployRemoveFolderStatusbarProgress {
            get {
                return ResourceManager.GetString("RemoteCommandDeployRemoveFolderStatusbarProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing VS Code Debugger.
        /// </summary>
        public static string RemoteCommandInstallDebuggerCommandCaption {
            get {
                return ResourceManager.GetString("RemoteCommandInstallDebuggerCommandCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing VS Code Debugger on targets ....
        /// </summary>
        public static string RemoteCommandInstallDebuggerCommandStatusbarProgress {
            get {
                return ResourceManager.GetString("RemoteCommandInstallDebuggerCommandStatusbarProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing VS Code Debugger from host.
        /// </summary>
        public static string RemoteCommandInstallDebuggerOfflineCommonProgress {
            get {
                return ResourceManager.GetString("RemoteCommandInstallDebuggerOfflineCommonProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing VS Code Debugger from host FAILED: {0}.
        /// </summary>
        public static string RemoteCommandInstallDebuggerOfflineCompletedFailed {
            get {
                return ResourceManager.GetString("RemoteCommandInstallDebuggerOfflineCompletedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing VS Code Debugger from host OK.
        /// </summary>
        public static string RemoteCommandInstallDebuggerOfflineCompletedSuccess {
            get {
                return ResourceManager.GetString("RemoteCommandInstallDebuggerOfflineCompletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading - URL: {0}, Version: {1}, RuntimeID: {2} .
        /// </summary>
        public static string RemoteCommandInstallDebuggerOfflineOutputPaneProgressDownloading {
            get {
                return ResourceManager.GetString("RemoteCommandInstallDebuggerOfflineOutputPaneProgressDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing .
        /// </summary>
        public static string RemoteCommandInstallDebuggerOfflineOutputPaneProgressInstalling {
            get {
                return ResourceManager.GetString("RemoteCommandInstallDebuggerOfflineOutputPaneProgressInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing VS Code Debugger direct from internet.
        /// </summary>
        public static string RemoteCommandInstallDebuggerOnlineCommonProgress {
            get {
                return ResourceManager.GetString("RemoteCommandInstallDebuggerOnlineCommonProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing VS Code Debugger direct from internet FAILED: {0}.
        /// </summary>
        public static string RemoteCommandInstallDebuggerOnlineCompletedFailed {
            get {
                return ResourceManager.GetString("RemoteCommandInstallDebuggerOnlineCompletedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing .NET.
        /// </summary>
        public static string RemoteCommandInstallDotnetCommandCaption {
            get {
                return ResourceManager.GetString("RemoteCommandInstallDotnetCommandCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing .NET on targets ....
        /// </summary>
        public static string RemoteCommandInstallDotnetCommandStatusbarText {
            get {
                return ResourceManager.GetString("RemoteCommandInstallDotnetCommandStatusbarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading binaries - URL: {0} .
        /// </summary>
        public static string RemoteCommandInstallDotnetOfflineOutputPaneDownloadingPayload {
            get {
                return ResourceManager.GetString("RemoteCommandInstallDotnetOfflineOutputPaneDownloadingPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading script - URL: {0}, RuntimeID: {1} .
        /// </summary>
        public static string RemoteCommandInstallDotnetOfflineOutputPaneDownloadingScript {
            get {
                return ResourceManager.GetString("RemoteCommandInstallDotnetOfflineOutputPaneDownloadingScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped downloading, use cache - file: {0}.
        /// </summary>
        public static string RemoteCommandInstallDotnetOfflineOutputPaneDownloadingSkipped {
            get {
                return ResourceManager.GetString("RemoteCommandInstallDotnetOfflineOutputPaneDownloadingSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing, this may take a while - file: {0} .
        /// </summary>
        public static string RemoteCommandInstallDotnetOfflineOutputPaneInstalling {
            get {
                return ResourceManager.GetString("RemoteCommandInstallDotnetOfflineOutputPaneInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading binaries - target: {0} .
        /// </summary>
        public static string RemoteCommandInstallDotnetOfflineOutputPaneUploadingPayload {
            get {
                return ResourceManager.GetString("RemoteCommandInstallDotnetOfflineOutputPaneUploadingPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing .NET runtime from host FAILED: {0}.
        /// </summary>
        public static string RemoteCommandInstallDotnetRuntimeOfflineCompletedFailed {
            get {
                return ResourceManager.GetString("RemoteCommandInstallDotnetRuntimeOfflineCompletedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing .NET runtime from host OK.
        /// </summary>
        public static string RemoteCommandInstallDotnetRuntimeOfflineCompletedSuccess {
            get {
                return ResourceManager.GetString("RemoteCommandInstallDotnetRuntimeOfflineCompletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing .NET runtime from host.
        /// </summary>
        public static string RemoteCommandInstallDotnetRuntimeOfflineOutputPaneProgress {
            get {
                return ResourceManager.GetString("RemoteCommandInstallDotnetRuntimeOfflineOutputPaneProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing .NET runtime direct from internet FAILED: {0}.
        /// </summary>
        public static string RemoteCommandInstallDotnetRuntimeOnlineCompletedFailed {
            get {
                return ResourceManager.GetString("RemoteCommandInstallDotnetRuntimeOnlineCompletedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing .NET runtime direct from internet OK.
        /// </summary>
        public static string RemoteCommandInstallDotnetRuntimeOnlineCompletedSuccess {
            get {
                return ResourceManager.GetString("RemoteCommandInstallDotnetRuntimeOnlineCompletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing .NET runtime direct from internet.
        /// </summary>
        public static string RemoteCommandInstallDotnetRuntimeOnlineOutputPaneProgress {
            get {
                return ResourceManager.GetString("RemoteCommandInstallDotnetRuntimeOnlineOutputPaneProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading .NET - Powershell script execution failed with &apos;{0}&apos;.
        /// </summary>
        public static string RemoteCommandInstallDotnetScriptExecutionFailed {
            get {
                return ResourceManager.GetString("RemoteCommandInstallDotnetScriptExecutionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing .NET SDK from host FAILED: {0}.
        /// </summary>
        public static string RemoteCommandInstallDotnetSdkOfflineCompletedFailed {
            get {
                return ResourceManager.GetString("RemoteCommandInstallDotnetSdkOfflineCompletedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing .NET SDK from host OK.
        /// </summary>
        public static string RemoteCommandInstallDotnetSdkOfflineCompletedSuccess {
            get {
                return ResourceManager.GetString("RemoteCommandInstallDotnetSdkOfflineCompletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing .NET SDK from host.
        /// </summary>
        public static string RemoteCommandInstallDotnetSdkOfflineOutputPaneProgress {
            get {
                return ResourceManager.GetString("RemoteCommandInstallDotnetSdkOfflineOutputPaneProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing .NET SDK direct from internet FAILED: {0}.
        /// </summary>
        public static string RemoteCommandInstallDotnetSdkOnlineCompletedFailed {
            get {
                return ResourceManager.GetString("RemoteCommandInstallDotnetSdkOnlineCompletedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing .NET SDK direct from internet OK.
        /// </summary>
        public static string RemoteCommandInstallDotnetSdkOnlineCompletedSuccess {
            get {
                return ResourceManager.GetString("RemoteCommandInstallDotnetSdkOnlineCompletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing .NET SDK direct from internet.
        /// </summary>
        public static string RemoteCommandInstallDotnetSdkOnlineOutputPaneProgress {
            get {
                return ResourceManager.GetString("RemoteCommandInstallDotnetSdkOnlineOutputPaneProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ok.
        /// </summary>
        public static string RemoteCommandUploadOutputPaneDone {
            get {
                return ResourceManager.GetString("RemoteCommandUploadOutputPaneDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string RemoteCommandUploadOutputPaneProgress {
            get {
                return ResourceManager.GetString("RemoteCommandUploadOutputPaneProgress", resourceCulture);
            }
        }
    }
}
