//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteDebuggerLauncher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RemoteDebuggerLauncher.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonLabel {
            get {
                return ResourceManager.GetString("CancelButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online: Target device has internet access, can download and install in it&apos;s own
        ///Offline: Target device no internet access, PC will download and trigger install.
        /// </summary>
        public static string InstallationModeDescription {
            get {
                return ResourceManager.GetString("InstallationModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string InstallationModeOfflineDisplayName {
            get {
                return ResourceManager.GetString("InstallationModeOfflineDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string InstallationModeOnlineDisplayName {
            get {
                return ResourceManager.GetString("InstallationModeOnlineDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDK: Install the full .NET SDK
        ///Runtime dotnet: Install only the .NET runtime
        ///Runtime aspnet: Install the ASP.NET runtime.
        /// </summary>
        public static string InstallationTypeDescription {
            get {
                return ResourceManager.GetString("InstallationTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime: aspnet.
        /// </summary>
        public static string InstallationTypeRuntimeAspnetDisplayName {
            get {
                return ResourceManager.GetString("InstallationTypeRuntimeAspnetDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime: dotnet.
        /// </summary>
        public static string InstallationTypeRuntimeNetDisplayName {
            get {
                return ResourceManager.GetString("InstallationTypeRuntimeNetDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDK.
        /// </summary>
        public static string InstallationTypeSdkDisplayName {
            get {
                return ResourceManager.GetString("InstallationTypeSdkDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the version of .NET and installation type, then click OK to install..
        /// </summary>
        public static string InstallDotnetDialogHeaderText {
            get {
                return ResourceManager.GetString("InstallDotnetDialogHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Mode.
        /// </summary>
        public static string InstallDotnetDialogModeLabel {
            get {
                return ResourceManager.GetString("InstallDotnetDialogModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install .NET on target host.
        /// </summary>
        public static string InstallDotnetDialogTitle {
            get {
                return ResourceManager.GetString("InstallDotnetDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Type.
        /// </summary>
        public static string InstallDotnetDialogTypeLabel {
            get {
                return ResourceManager.GetString("InstallDotnetDialogTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string InstallDotnetDialogVersionLabel {
            get {
                return ResourceManager.GetString("InstallDotnetDialogVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkButtonLabel {
            get {
                return ResourceManager.GetString("OkButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string VersionCurrentDisplayName {
            get {
                return ResourceManager.GetString("VersionCurrentDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current: The most recent current version of .NET
        ///LTS: The most recent LTS version of .NET.
        /// </summary>
        public static string VersionDescription {
            get {
                return ResourceManager.GetString("VersionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LTS.
        /// </summary>
        public static string VersionLtsDisplayName {
            get {
                return ResourceManager.GetString("VersionLtsDisplayName", resourceCulture);
            }
        }
    }
}
