name: 'Project: Release'
# shall trigger on the main branch when a tag named 'v*' gets created
on: 
  push:
    branches:
    - main
    tags:
    -  v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Release Build
    uses: ./.github/workflows/shared-build.yml
    with:
      store-artifacts: true

  github-release:
    name: GitHub Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    if: ${{ github.ref_type == 'tag' }}

    env:
      GitHubReleaseBodyFile: ${{ github.workspace }}/src/ReleaseNotes.md

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download artifacts
      id: download
      uses: actions/download-artifact@v3
      with:
        name: vsix

#     - run: echo ${{steps.download.outputs.download-path}}
#     - name: Display structure of downloaded files
#       run: ls -R

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
         artifacts: '${{steps.download.outputs.download-path}}/RemoteDebuggerLauncher.vsix'
         bodyFile: ${{ env.GitHubReleaseBodyFile }}


  marketplace-release:
    name: VS Marketplace Release
    runs-on: windows-2022
    needs: build
    if: ${{ github.ref_type == 'tag' }}

    steps:
    - name: TODO
      run: echo TODO