name: 'Project: Release'
# shall trigger on the main branch when a tag named 'v*' gets created
on: 
  push:
    branches:
    - main
    tags:
    -  v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Release Build
    uses: ./.github/workflows/shared-build.yml
    with:
      store-artifacts: true

  github-release:
    name: GitHub Release
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref_type == 'tag' }}

    steps:
    - name: Dummy
      run: echo TODO

  marketplace-release:
    name: VS Marketplace Release
    runs-on: windows-2022
    needs: build
    if: ${{ github.ref_type == 'tag' }}

    steps:
    - name: Dummy
      run: echo TODO